### ISSUE TITLE
How does dependency get inject to app?

### ISSUE THREAD

**Issue by devGitAbhishek** [rtivital/react-monorepo-starter#3]
In app package file you are declaring package dependency, how is it getting injected with @scope?

**Comment by rtivital** [comment]
It is done with webpack alias – https://github.com/rtivital/react-monorepo-starter/blob/master/webpack/get-package-config.js#L25

**Comment by devGitAbhishek** [comment]
Oh ok I need one help

So I am trying to make shared package lib in a monorepo based approach ,

I am trying to use that package as dependency in the app by including in package.json of app.


Now app is is CRA based and package folder is getting build by  webpack, but when I run the app in browser I get error as Object is not a function

I am not using your template

**Comment by rtivital** [comment]
`Object is not a function` error usually means that you've imported package incorrectly, for example, when you've used `import a from 'a'` instead of `import { a } from 'a'`

**Comment by devGitAbhishek** [comment]
Ok Could you please share me some example of how to have CRA in monorepo without craco or react-app-rewired and using webpack for shared package and using in our app?

**Comment by devGitAbhishek** [comment]
Edited above comment

**Comment by rtivital** [comment]
I haven't used CRA in monorepo and do not have any examples, you can eject the app and edit webpack config.
